services:
  - type: web
    name: ransa-control-viajes
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: SUPABASE_HOST
        sync: false
      - key: SUPABASE_USER
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
      - key: SUPABASE_PORT
        value: "5432"
      - key: SUPABASE_DB
        value: "postgres"
